---
deployment:
  tasks:
    - export DEPLOYPATH=/home/$USER/carini
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R . $DEPLOYPATH
    - cd $DEPLOYPATH && npm install --omit=dev
    - cd $DEPLOYPATH/frontend && npm install && npm run build
